### PR TITLE
Problem: pulp 2 service names conflict with pulp 3 service names

### PR DESCRIPTION
**Pull request by dkliban**
Solution: rename conflicting pulp 2 services

re: #4554
https://pulp.plan.io/issues/4554

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I'd be *very* cautious with this. A lot of tooling depends on this. Just speaking about the foreman ecosystem, it's foreman-maintain which has logic to start/stop/check services. Then we also have puppet-pulp which ensures the services are started and enabled. I can also imagine a lot of users have monitoring (nagios, icinga, whatever) to check whether a service is up. This will be a major breaking change for that.

I would strongly consider renaming pulp3 services.

**Comment by dkliban** [comment]
@ekohl We will rename the pulp 3 services. Thanks!

**Comment by ekohl** [comment]
Will they become `pulpcore-*` now?

**Comment by dkliban** [comment]
@ekohl Yes, I believe so.

**Pull request closed without merging**
